Plan: Use one-hot encoder to turn categorical data into numerical data, do descriptive statistics on numerical data (back to basics like I did before) (the descriptive statistic themselves tell a story already, ex. drivers in a certain age group are more likely to crash than in another age group) + (if I have time) do geospatial analysis and cross-reference it with the statistics I have

In [71]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [72]:
file = r'''/Users/aaronhxzhang/AARD/Data/OneHotEncodingCrashData.xlsx'''
data = pd.ExcelFile(file)
df1 = data.parse('Sheet1')
df1

Crash Number Crash Date Crash Time          Crash Hour City/Town  \
0          4031891 2015-03-12   18:00:00  06:00PM to 06:59PM     ACTON   
1          4031895 2015-03-14   13:12:00  01:00PM to 01:59PM     ACTON   
2          4031912 2015-03-18   17:41:00  05:00PM to 05:59PM     ACTON   
3          4017549 2015-01-24   16:30:00  04:00PM to 04:59PM     ACTON   
4          4026497 2015-03-19   08:32:00  08:00AM to 08:59AM     ACTON   
5          4032077 2015-02-23   18:24:00  06:00PM to 06:59PM     ACTON   
6          4032079 2015-02-20   13:07:00  01:00PM to 01:59PM     ACTON   
7          4012454 2015-01-09   10:30:00  10:00AM to 10:59AM     ACTON   
8          4012461 2015-01-09   09:04:00  09:00AM to 09:59AM     ACTON   
9          4012471 2015-01-06   12:26:00  12:00PM to 12:59PM     ACTON   
10         4012568 2015-01-19   05:54:00  05:00AM to 05:59AM     ACTON   
11         4033231 2015-02-19   17:08:00  05:00PM to 05:59PM     ACTON   
12         4065693 2015-07-08   08:13:00  08:00AM to 08:59AM     ACTON   
13         4011187 2014-12-20   14:38:00  02:00PM to 02:59PM     ACTON   
14         4011211 2014-12-18   17:55:00  05:00PM to 05:59PM     ACTON   
15         4012081 2014-11-12   06:19:00  06:00AM to 06:59AM     ACTON   
16         4033232 2015-02-24   08:10:00  08:00AM to 08:59AM     ACTON   
17         4035271 2015-02-16   15:56:00  03:00PM to 03:59PM     ACTON   
18         4035279 2015-02-13   09:23:00  09:00AM to 09:59AM     ACTON   
19         4035283 2015-02-14   15:11:00  03:00PM to 03:59PM     ACTON   
20         4037512 2015-03-04   15:23:00  03:00PM to 03:59PM     ACTON   
21         4037513 2015-03-03   07:31:00  07:00AM to 07:59AM     ACTON   
22         4040739 2015-03-21   14:32:00  02:00PM to 02:59PM     ACTON   
23         4040746 2015-03-18   17:56:00  05:00PM to 05:59PM     ACTON   
24         3994688 2014-12-10   15:16:00  03:00PM to 03:59PM     ACTON   
25         3994708 2014-12-09   16:12:00  04:00PM to 04:59PM     ACTON   
26         3994711 2014-12-15   12:05:00  12:00PM to 12:59PM     ACTON   
27         3996538 2014-11-07   21:28:00  09:00PM to 09:59PM     ACTON   
28         4003008 2014-11-12   12:35:00  12:00PM to 12:59PM     ACTON   
29         4003010 2014-11-13   08:33:00  08:00AM to 08:59AM     ACTON   
...            ...        ...        ...                 ...       ...   
1034       4379536 2017-06-09   06:54:00  06:00AM to 06:59AM     ACTON   
1035       4386272 2017-06-18   18:46:00  06:00PM to 06:59PM     ACTON   
1036       4391283 2017-06-26   12:47:00  12:00PM to 12:59PM     ACTON   
1037       4391287 2017-07-09   19:53:00  07:00PM to 07:59PM     ACTON   
1038       4394462 2017-07-14   17:48:00  05:00PM to 05:59PM     ACTON   
1039       4396410 2017-07-06   15:00:00  03:00PM to 03:59PM     ACTON   
1040       4404766 2017-07-30   15:06:00  03:00PM to 03:59PM     ACTON   
1041       4404819 2017-07-20   08:18:00  08:00AM to 08:59AM     ACTON   
1042       4406404 2017-07-21   14:36:00  02:00PM to 02:59PM     ACTON   
1043       4407707 2017-08-13   08:20:00  08:00AM to 08:59AM     ACTON   
1044       4414817 2017-08-20   10:23:00  10:00AM to 10:59AM     ACTON   
1045       4414819 2017-08-15   19:01:00  07:00PM to 07:59PM     ACTON   
1046       4421496 2017-08-31   16:33:00  04:00PM to 04:59PM     ACTON   
1047       4433970 2017-08-25   17:32:00  05:00PM to 05:59PM     ACTON   
1048       4433972 2017-08-26   18:19:00  06:00PM to 06:59PM     ACTON   
1049       4436639 2017-08-25   07:17:00  07:00AM to 07:59AM     ACTON   
1050       4439423 2017-09-24   13:44:00  01:00PM to 01:59PM     ACTON   
1051       4439424 2017-09-25   09:36:00  09:00AM to 09:59AM     ACTON   
1052       4439428 2017-09-26   15:11:00  03:00PM to 03:59PM     ACTON   
1053       4446021 2017-09-17   16:55:00  04:00PM to 04:59PM     ACTON   
1054       4447757 2017-10-22   10:53:00  10:00AM to 10:59AM     ACTON   
1055       4457332 2017-11-16   13:15:00  01:00PM to 01:59PM     ACTON   
1056      

1. find all unique possibilities for a certain feature (ex. weather)
1a. if needed, reduce the number of possibilities (ex. group fog/fog and rain/fog together)
2. sort that array of possibilities using .sort()
3. give each unique possibility for a feature a numerical index index
4. fit_transform the array of unique numbers 'feat_idx' you have
5. OneHotEncoder(**) should give you an array of arrays of unique indices you have 

In [73]:
df1.columns


Index(['Crash Number', 'Crash Date', 'Crash Time', 'Crash Hour', 'City/Town',
       'Locality', 'Crash Severity', 'Maximum Injury Severity Reported',
       'Number of NonFatal Injuries', 'Number of Fatal Injuries',
       'Number of Vehicles', 'Manner of Collision',
       'Age of Driver - Youngest Known', 'Age of Driver - Oldest Known',
       'Hit & Run', 'Road Surface', 'Ambient Light', 'Weather Condition',
       'Traffic Way', 'Speed Limit', 'Roadway Intersection Type',
       'Linked RI Number of Travel Lanes', 'Linked RI Street Operation',
       'Linked RI Average Daily Traffic', 'Linked RI Year of ADT', 'X', 'Y',
       'Road Segment ID', 'County'],
      dtype='object')

# Weather Condition

In [74]:
df1['Weather Condition'].unique()

array(['Clear/Clear', 'Rain/Cloudy', 'Not Reported', 'Snow/Snow', 'Clear',
       'Snow', 'Snow/Cloudy', 'Cloudy/Cloudy', 'Cloudy', 'Clear/Cloudy',
       'Rain/Fog, smog, smoke', 'Cloudy/Other', 'Rain/Rain', 'Rain',
       'Snow/Sleet, hail (freezing rain or drizzle)', 'Cloudy/Snow',
       'Clear/Other', 'Cloudy/Clear', 'Cloudy/Rain',
       'Rain/Sleet, hail (freezing rain or drizzle)',
       'Snow/Blowing sand, snow', 'Clear/Unknown',
       'Snow/Severe crosswinds', 'Clear/Rain', 'Snow/Rain',
       'Fog, smog, smoke/Rain',
       'Cloudy/Sleet, hail (freezing rain or drizzle)', 'Rain/Snow'],
      dtype=object)

In [75]:
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Clear/Unknown', 'Clear', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Clear/Cloudy', 'Clear', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Clear/Clear', 'Clear', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Clear/Other', 'Clear', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Clear', 'Clear', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy/Rain', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Cloudy', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Clear/Rain', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Rain', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy', 'Cloudy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy/Clear', 'Cloudy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy/Unknown', 'Cloudy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy/Cloudy', 'Cloudy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy/Other', 'Cloudy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow/Other', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow/Cloudy', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Snow', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow/Rain', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Fog, smog, smoke', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Unknown', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Other', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Clear', 'Rainy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Not Reported', 'Unknown', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Unknown', 'Unknown', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Unknown/Other', 'Unknown', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Unknown/Unknown', 'Unknown', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Sleet, hail (freezing rain or drizzle)', 'Sleet/Hail', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Rain/Sleet, hail (freezing rain or drizzle)', 'Sleet/Hail', df1['Weather Condition'])
df1['Weather Condition'].unique()

array(['Clear', 'Rainy', 'Unknown', 'Snow/Snow', 'Snowy', 'Cloudy',
       'Snow/Sleet, hail (freezing rain or drizzle)', 'Cloudy/Snow',
       'Sleet/Hail', 'Snow/Blowing sand, snow', 'Snow/Severe crosswinds',
       'Fog, smog, smoke/Rain',
       'Cloudy/Sleet, hail (freezing rain or drizzle)'], dtype=object)

In [76]:
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow/Snow', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy/Snow', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Blowing sand, snow', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow/Severe crosswinds', 'Severe crosswinds', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Severe crosswinds/Blowing sand, snow', 'Severe crosswinds', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Cloudy/Sleet, hail (freezing rain or drizzle)', 'Sleet/Hail', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow/Sleet, hail (freezing rain or drizzle)', 'Sleet/Hail', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Snow/Blowing sand, snow', 'Snowy', df1['Weather Condition'])
df1['Weather Condition']=np.where(df1['Weather Condition'] =='Fog, smog, smoke/Rain', 'Rainy', df1['Weather Condition'])
df1['Weather Condition'].unique()

array(['Clear', 'Rainy', 'Unknown', 'Snowy', 'Cloudy', 'Sleet/Hail',
       'Severe crosswinds'], dtype=object)

In [77]:
a = df1['Weather Condition'].unique()
a.sort()
a

array(['Clear', 'Cloudy', 'Rainy', 'Severe crosswinds', 'Sleet/Hail',
       'Snowy', 'Unknown'], dtype=object)

In [78]:
#Ask justin how to get the step between where you get to see both the condition and the number that it corresponds to
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [79]:
label_encoder = LabelEncoder()

In [80]:
feat_idx = label_encoder.fit_transform(a)
feat_idx

array([0, 1, 2, 3, 4, 5, 6])

In [81]:
onehot_encoder = OneHotEncoder(sparse=False)
feat_idx = feat_idx.reshape(len(feat_idx), 1)
weather_encoded = onehot_encoder.fit_transform(feat_idx)
weather_encoded    #should be onehot_encoded now

/Users/aaronhxzhang/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [82]:
df1.groupby('Weather Condition').mean()

Crash Number  Number of NonFatal Injuries  \
Weather Condition                                              
Clear              4.138406e+06                     0.307692   
Cloudy             4.114645e+06                     0.244275   
Rainy              4.169143e+06                     0.330827   
Severe crosswinds  4.008616e+06                     0.000000   
Sleet/Hail         4.126714e+06                     0.000000   
Snowy              4.065229e+06                     0.118421   
Unknown            4.100552e+06                     0.166667   

                   Number of Fatal Injuries  Number of Vehicles  Speed Limit  \
Weather Condition                                                              
Clear                              0.004274            1.884615    29.495726   
Cloudy                             0.000000            1.908397    30.648855   
Rainy                              0.000000            1.714286    33.007519   
Severe crosswinds                  0.000000            1.500000    17.500000   
Sleet/Hail                         0.000000            1.428571    25.714286   
Snowy                              0.013158            1.447368    30.000000   
Unknown                            0.000000            1.833333    23.333333   

                   Linked RI Number of Travel Lanes  \
Weather Condition                                     
Clear                                      1.984330   
Cloudy                                     1.984733   
Rainy                                      1.992481   
Severe crosswinds                          1.500000   
Sleet/Hail                                 2.000000   
Snowy                                      1.986842   
Unknown                                    2.000000   

                   Linked RI Average Daily Traffic  Linked RI Year of ADT  \
Weather Condition                                                           
Clear                                 14505.890157            1788.139800   
Cloudy                                15336.954198            1781.404580   
Rainy                                 19376.135338            1815.278195   
Severe crosswinds                       700.000000               0.000000   
Sleet/Hail                            12104.000000            1293.500000   
Snowy                                 12835.684211            1614.631579   
Unknown                               13570.500000            1341.333333   

                               X              Y  Road Segment ID  
Weather Condition                                                 
Clear              204902.772105  914401.171466      2155.092593  
Cloudy             205058.598996  914390.101413      1783.595420  
Rainy              204647.127495  914517.512128      3405.383459  
Severe crosswinds  205155.680863  915002.898928      1603.500000  
Sleet/Hail         205147.584563  914396.277582      1723.357143  
Snowy              204851.007653  914118.302382      1783.855263  
Unknown            204112.419599  914478.953912      1826.166667

# Age of Youngest Driver 

In [83]:
df1['Age of Driver - Youngest Known'].unique()

array(['16-20', '25-34', '45-54', '65-74', '55-64', '35-44', '21-24',
       '75-84', '>84'], dtype=object)

In [84]:
a = df1['Age of Driver - Youngest Known'].unique()
a.sort()
a

array(['16-20', '21-24', '25-34', '35-44', '45-54', '55-64', '65-74',
       '75-84', '>84'], dtype=object)

In [85]:
feat_idx = label_encoder.fit_transform(a)
feat_idx

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
onehot_encoder = OneHotEncoder(sparse=False)
feat_idx = feat_idx.reshape(len(feat_idx), 1)
youngest_encoded = onehot_encoder.fit_transform(feat_idx)
youngest_encoded    #should be onehot_encoded now

/Users/aaronhxzhang/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [88]:
df1.groupby('Age of Driver - Youngest Known').mean()

Crash Number  Number of NonFatal Injuries  \
Age of Driver - Youngest Known                                              
16-20                           4.148494e+06                     0.207373   
21-24                           4.115863e+06                     0.353333   
25-34                           4.147047e+06                     0.327434   
35-44                           4.119170e+06                     0.314607   
45-54                           4.122946e+06                     0.254438   
55-64                           4.154211e+06                     0.267442   
65-74                           4.087376e+06                     0.172414   
75-84                           4.149899e+06                     0.250000   
>84                             4.206882e+06                     1.000000   

                                Number of Fatal Injuries  Number of Vehicles  \
Age of Driver - Youngest Known                                                 
16-20                                           0.000000            1.903226   
21-24                                           0.000000            1.846667   
25-34                                           0.000000            1.876106   
35-44                                           0.005618            1.904494   
45-54                                           0.005917            1.781065   
55-64                                           0.023256            1.569767   
65-74                                           0.000000            1.551724   
75-84                                           0.000000            1.250000   
>84                                             0.000000            1.000000   

                                Speed Limit  Linked RI Number of Travel Lanes  \
Age of Driver - Youngest Known                                                  
16-20                             29.792627                          1.986175   
21-24                             29.766667                          1.993333   
25-34                             33.274336                          1.986726   
35-44                             30.455056                          1.977528   
45-54                             26.242604                          1.988166   
55-64                             29.011628                          1.988372   
65-74                             31.551724                          1.931034   
75-84                             22.500000                          2.000000   
>84                               30.000000                          2.000000   

                                Linked RI Average Daily Traffic  \
Age of Driver - Youngest Known                                    
16-20                                              13100.375000   
21-24                                              16296.406667   
25-34                                              18066.287611   
35-44                                              15169.764045   
45-54                                              12766.704142   
55-64                                              13185.511628   
65-74                                              18326.379310   
75-84                                              11783.250000   
>84                                                 7988.000000   

                                Linked RI Year of ADT              X  \
Age of Driver - Youngest Known                                         
16-20                                     1741.990741  204582.167729   
21-24                                     1716.846667  204929.293195   
25-34                                     1842.774336  204961.543177   
35-44                                     1774.410112  205040.168689   
45-54                                     1738.094675  204929.412040   
55-64                                     1778.139535  205010.285652   
65-74                                     1664.965517  204999.289843   
75-84                    

# Road Surface

In [90]:
df1['Road Surface'].unique()

array(['Wet', 'Dry', 'Snow', 'Ice', 'Sand, mud, dirt, oil, gravel',
       'Not reported', 'Water (standing, moving)', 'Slush'], dtype=object)

In [93]:
df1['Road Surface']=np.where(df1['Road Surface'] =='Water (standing, moving)', 'Wet', df1['Road Surface'])
df1['Road Surface']=np.where(df1['Road Surface'] =='Slush', 'Wet', df1['Road Surface'])
df1['Road Surface'].unique()

array(['Wet', 'Dry', 'Snow', 'Ice', 'Sand, mud, dirt, oil, gravel',
       'Not reported'], dtype=object)

In [94]:
a = df1['Road Surface'].unique()
a.sort()
a

array(['Dry', 'Ice', 'Not reported', 'Sand, mud, dirt, oil, gravel',
       'Snow', 'Wet'], dtype=object)

In [95]:
feat_idx = label_encoder.fit_transform(a)
feat_idx

array([0, 1, 2, 3, 4, 5])

In [96]:
onehot_encoder = OneHotEncoder(sparse=False)
feat_idx = feat_idx.reshape(len(feat_idx), 1)
roadSurface_encoded = onehot_encoder.fit_transform(feat_idx)
roadSurface_encoded    #should be onehot_encoded now

/Users/aaronhxzhang/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Ambient Light

In [99]:
df1['Ambient Light']=np.where(df1['Ambient Light'] =='Not reported', 'Unknown', df1['Ambient Light'])
df1['Ambient Light']=np.where(df1['Ambient Light'] =='Other', 'Unknown', df1['Ambient Light'])
df1['Ambient Light'].unique()

array(['Daylight', 'Dark - roadway not lighted', 'Dusk',
       'Dark - lighted roadway', 'Dawn',
       'Dark - unknown roadway lighting', 'Unknown'], dtype=object)

In [101]:
a = df1['Road Surface'].unique()
a.sort()
feat_idx = label_encoder.fit_transform(a)
onehot_encoder = OneHotEncoder(sparse=False)
feat_idx = feat_idx.reshape(len(feat_idx), 1)
light_encoded = onehot_encoder.fit_transform(feat_idx)
a, feat_idx, light_encoded    #should be onehot_encoded now

/Users/aaronhxzhang/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


(array(['Dry', 'Ice', 'Not reported', 'Sand, mud, dirt, oil, gravel',
        'Snow', 'Wet'], dtype=object), array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]), array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]))

# Manner of Collision

In [102]:
df1['Manner of Collision'].unique()

array(['Single vehicle crash', 'Angle', 'Unknown',
       'Sideswipe, same direction', 'Rear-end', 'Rear-to-rear',
       'Sideswipe, opposite direction', 'Head-on', 'Not reported'],
      dtype=object)

In [105]:
df1['Manner of Collision']=np.where(df1['Manner of Collision'] =='Sideswipe, opposite direction', 'Sideswipe', df1['Manner of Collision'])
df1['Manner of Collision']=np.where(df1['Manner of Collision'] =='Sideswipe, same direction', 'Sideswipe', df1['Manner of Collision'])
df1['Manner of Collision']=np.where(df1['Manner of Collision'] =='Rear-to-rear', 'Rear-end', df1['Manner of Collision'])
df1['Manner of Collision']=np.where(df1['Manner of Collision'] == 'Not reported', 'Unknown', df1['Manner of Collision'])
df1['Manner of Collision'].unique()

array(['Single vehicle crash', 'Angle', 'Unknown', 'Sideswipe',
       'Rear-end', 'Head-on'], dtype=object)

# Roadway Intersection Type 